version: "3.3"
services:
  backend-app:
    build: ./backend-app
    ports:
      - 8080:8080
    volumes:
      - ./backend-app/src:/backend-app/src/
    depends_on:
      - local-db
  local-db:
    build: ./local-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mower 
      POSTGRES_PASSWORD: mower123 