version: "3.8"
services:
  backend-app:
    build: ./backend-app
    ports:
      - 8080:8080
    volumes:
      - ./backend-app/src:/backend-app/src/
  local-db:
    build: ./local-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: moover 
      POSTGRES_PASSWORD: moover123 