name: CI Backend-application

on: push

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    env:
      working-directory: ./backend-app
    steps:
    - uses: actions/checkout@v2
    - run: pwd && ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build